# Generated by Django 3.2.9 on 2022-01-19 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AdicionalOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('nombre_adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frutales_app.adicional')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('precio', models.CharField(max_length=90)),
                ('tamaño', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.TimeField(auto_now=True)),
                ('updated_at', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamañoproducto', models.CharField(max_length=100)),
                ('especificaciones', models.TextField()),
                ('entrega', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('globoadicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='globos', to='frutales_app.adicionalorden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frutales_app.producto')),
                ('rosaadicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosas', to='frutales_app.adicionalorden')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frutales_app.usuario')),
            ],
        ),
    ]
