# Generated by Django 3.2.9 on 2021-12-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutales_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('tamaño', models.CharField(max_length=10)),
            ],
        ),
    ]
