# Generated by Django 3.2.9 on 2021-12-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutales_app', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(choices=[('peq', 'Pequeño'), ('med', 'Mediano'), ('gran', 'Grande')], default='med', max_length=10),
        ),
    ]
