# Generated by Django 3.2.9 on 2021-12-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutales_app', '0003_alter_producto_tamaño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(max_length=22),
        ),
    ]
