# Generated by Django 3.2.9 on 2021-12-30 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frutales_app', '0004_auto_20211227_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdicionalOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('nombre_adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frutales_app.adicional')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamañoproducto', models.CharField(max_length=100)),
                ('especificaciones', models.TextField()),
                ('entrega', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('globoadicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='globos', to='frutales_app.adicionalorden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frutales_app.producto')),
                ('rosaadicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosas', to='frutales_app.adicionalorden')),
            ],
        ),
    ]
