# Generated by Django 3.2.9 on 2021-12-30 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frutales_app', '0005_auto_20211230_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adicional',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
