# Generated by Django 3.2.9 on 2021-12-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutales_app', '0006_rename_nombre_adicional_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicional',
            name='precio',
            field=models.FloatField(),
        ),
    ]
