# Generated by Django 3.2.9 on 2022-01-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frutales_app', '0007_alter_adicional_precio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
    ]
